---
  - name: "Konfiguration von Mesh- und Client-VLAN"
    template: 
      src: templates/interfaces_mesh_mit_client.j2
      dest: /etc/network/interfaces
    when: ( raspberry_clientvlan|length > 0 ) and ( raspberry_meshvlan|length > 0 )
