---
  - name: "lokale link-local IPv6 Adresse aus dem PUBLIC-Key erzeugen"
    shell: cat /etc/wireguard/client_public.key | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/fe80::02\1:\2ff:fe\3:\4\5/'
    register: wg_node_linklocal 

  - name: "checkupscript zum Testen der wireguard-Verbindung anlegen"
    template:
      src: templates/checkup.j2
      dest: /usr/local/bin/checkup

  - name: "Ausführungsrechte des Bash-Scripts anpassen"
    file:
      path: /usr/local/bin/checkup
      mode: '0740'

  - name: "crontab für minütlichen checkup der wireguard-Verbindung anlegen"
    template:
      src: templates/crontab.j2
      dest: /etc/crontab
